name: raspicam
description: A dart wrapper for raspistill and raspivid (todo).
version: 1.0.1
repository: 'https://github.com/cthurston/raspicam_dart'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
 path: ^1.8.0-nullsafety.3

dev_dependencies:
  pedantic: ^1.9.0
  test:
